### ISSUE TITLE
Types won't import, even after following the instructions in README

### ISSUE THREAD

**Issue by hiimjasmine00** [SpaghettDev/BromaIDA#4]
![image](https://github.com/user-attachments/assets/997ad0bc-9fbb-40b3-972c-e5b13cd8519e)

**Comment by hiimjasmine00** [comment]
Happens with IDA Pro 8.3

**Comment by SpaghettDev** [comment]
this will be fixed in the next update (hopefully), i think #3 fixes this

**Comment by SpaghettDev** [comment]
#3 did in fact fix this
